name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 
      - 
        name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version:
            8.0   
      - 
        name: Install GitVersion
        run: dotnet tool install --global GitVersion.Tool
      - 
        name: Fetch GitVersion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true                 
      - 
        name: Create version tag on release
        if: github.ref == 'refs/heads/main'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ env.GitVersion_SemVer }}
          git push origin refs/tags/v${{ env.GitVersion_SemVer }} refs/heads/main
      - 
        name: Set environment variables for Docker tags
        run: |
          echo "DOCKER_TAG=${{ env.GitVersion_SemVer }}" >> $GITHUB_ENV
          if [[ "${GITHUB_REF##*/}" == "main" ]]; then
            echo "DOCKER_TAG2=stable" >> $GITHUB_ENV
          else
            echo "DOCKER_TAG2=latest" >> $GITHUB_ENV
          fi          
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2      
      - 
        name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/ballware/ballware-keycloak:${{ env.DOCKER_TAG }}
            ghcr.io/ballware/ballware-keycloak:${{ env.DOCKER_TAG2 }}  
